package com.settlement.entity;

public enum AuditEventType {
    INSTRUCTION_CREATED,
    INSTRUCTION_SENT,
    INSTRUCTION_FAILED,
    RETRIES_EXHAUSTED,
    MANUAL_RETRY,
    RECONCILE_UNMATCHED,
    SETTLEMENT_MATCHED,
    SETTLEMENT_FAILED,
    SETTLEMENT_PENDING,
    SETTLEMENT_STATUS_UNKNOWN,
    DVP_LOCKED,
    DVP_CASH_RESERVED,
    DVP_COMPLETED,
    DVP_FAILED,
    MATCHING_MATCHED,
    MATCHING_ALLEGED,
    SETTLEMENT_FINALIZED,
    PARTIAL_SETTLEMENT_CREATED,
    PARTIAL_SETTLEMENT_COMPLETED
}
