package com.settlement.entity;

public enum AuditEventType {
    INSTRUCTION_CREATED,
    INSTRUCTION_SENT,
    INSTRUCTION_FAILED,
    RETRIES_EXHAUSTED,
    MANUAL_RETRY,
    RECONCILE_UNMATCHED,
    SETTLEMENT_MATCHED,
    SETTLEMENT_FAILED,
    SETTLEMENT_PENDING,
    SETTLEMENT_STATUS_UNKNOWN
}
