-- Bond Settlement System - Oracle DDL

-- Settlement Instruction table (business entity — message-format agnostic)
CREATE TABLE SETTLEMENT_INSTRUCTION (
    ID                  NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TRADE_REF           VARCHAR2(50)  NOT NULL,
    ISIN                VARCHAR2(12)  NOT NULL,
    SETTLEMENT_DATE     DATE          NOT NULL,
    QUANTITY            NUMBER(18,2)  NOT NULL,
    COUNTERPARTY        VARCHAR2(100) NOT NULL,
    BIC_CODE            VARCHAR2(11)  NOT NULL,
    DIRECTION           VARCHAR2(10)  NOT NULL,
    STATUS              VARCHAR2(20)  DEFAULT 'PENDING' NOT NULL,
    ACCOUNT_ID          VARCHAR2(50)  NOT NULL,
    PREFERRED_STANDARD  VARCHAR2(5)   DEFAULT 'MT' NOT NULL,
    RETRY_COUNT         NUMBER(3)     DEFAULT 0 NOT NULL,
    FAILURE_REASON      VARCHAR2(1000),
    CREATED_AT          TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT          TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT UK_TRADE_REF UNIQUE (TRADE_REF),
    CONSTRAINT CK_DIRECTION CHECK (DIRECTION IN ('BUY', 'SELL')),
    CONSTRAINT CK_STATUS CHECK (STATUS IN ('PENDING', 'SUBMITTING', 'SENT', 'MATCHED', 'FAILED', 'RETRYING', 'CANCELLED')),
    CONSTRAINT CK_PREFERRED_STD CHECK (PREFERRED_STANDARD IN ('MT', 'MX'))
);

CREATE INDEX IDX_INSTRUCTION_STATUS ON SETTLEMENT_INSTRUCTION (STATUS);
CREATE INDEX IDX_INSTRUCTION_ISIN ON SETTLEMENT_INSTRUCTION (ISIN);
CREATE INDEX IDX_INSTRUCTION_DATE ON SETTLEMENT_INSTRUCTION (SETTLEMENT_DATE);

-- SWIFT Message store (decoupled from business entity, supports MT and MX)
CREATE TABLE SWIFT_MESSAGE (
    ID                NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    INSTRUCTION_ID    NUMBER         NOT NULL,
    TRADE_REF         VARCHAR2(50)   NOT NULL,
    MESSAGE_STANDARD  VARCHAR2(5)    NOT NULL,
    MESSAGE_TYPE      VARCHAR2(50)   NOT NULL,
    DIRECTION         VARCHAR2(10)   NOT NULL,
    RAW_PAYLOAD       CLOB           NOT NULL,
    NAMESPACE         VARCHAR2(200),
    BUSINESS_AREA     VARCHAR2(10),
    PARSED_STATUS     VARCHAR2(30),
    PARSED_REASON     VARCHAR2(500),
    SEQUENCE_NO       NUMBER(5)      DEFAULT 1 NOT NULL,
    CREATED_AT        TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_MSG_INSTRUCTION FOREIGN KEY (INSTRUCTION_ID)
        REFERENCES SETTLEMENT_INSTRUCTION(ID),
    CONSTRAINT CK_MSG_STANDARD CHECK (MESSAGE_STANDARD IN ('MT', 'MX')),
    CONSTRAINT CK_MSG_DIRECTION CHECK (DIRECTION IN ('OUTBOUND', 'INBOUND'))
);

CREATE INDEX IDX_MSG_INSTRUCTION ON SWIFT_MESSAGE (INSTRUCTION_ID);
CREATE INDEX IDX_MSG_TRADE_REF ON SWIFT_MESSAGE (TRADE_REF);
CREATE INDEX IDX_MSG_TYPE ON SWIFT_MESSAGE (MESSAGE_TYPE, DIRECTION);

-- Message Type Registry (MT ↔ MX mapping and metadata)
CREATE TABLE MESSAGE_TYPE_REGISTRY (
    MESSAGE_TYPE      VARCHAR2(50)   PRIMARY KEY,
    MESSAGE_STANDARD  VARCHAR2(5)    NOT NULL,
    DESCRIPTION       VARCHAR2(200)  NOT NULL,
    MT_EQUIVALENT     VARCHAR2(10),
    MX_EQUIVALENT     VARCHAR2(50),
    CATEGORY          VARCHAR2(30)   NOT NULL,
    IS_ACTIVE         NUMBER(1)      DEFAULT 1 NOT NULL,
    CONSTRAINT CK_REG_STANDARD CHECK (MESSAGE_STANDARD IN ('MT', 'MX')),
    CONSTRAINT CK_REG_CATEGORY CHECK (CATEGORY IN ('SETTLEMENT', 'STATUS', 'HOLDING', 'MOVEMENT', 'CONFIRMATION'))
);

INSERT INTO MESSAGE_TYPE_REGISTRY (MESSAGE_TYPE, MESSAGE_STANDARD, DESCRIPTION, MT_EQUIVALENT, MX_EQUIVALENT, CATEGORY)
    VALUES ('MT541', 'MT', 'Receive Against Payment', NULL, 'sese.023.001.09', 'SETTLEMENT');
INSERT INTO MESSAGE_TYPE_REGISTRY (MESSAGE_TYPE, MESSAGE_STANDARD, DESCRIPTION, MT_EQUIVALENT, MX_EQUIVALENT, CATEGORY)
    VALUES ('MT548', 'MT', 'Settlement Status and Processing Advice', NULL, 'sese.024.001.10', 'STATUS');
INSERT INTO MESSAGE_TYPE_REGISTRY (MESSAGE_TYPE, MESSAGE_STANDARD, DESCRIPTION, MT_EQUIVALENT, MX_EQUIVALENT, CATEGORY)
    VALUES ('sese.023.001.09', 'MX', 'Securities Settlement Transaction Instruction', 'MT541', NULL, 'SETTLEMENT');
INSERT INTO MESSAGE_TYPE_REGISTRY (MESSAGE_TYPE, MESSAGE_STANDARD, DESCRIPTION, MT_EQUIVALENT, MX_EQUIVALENT, CATEGORY)
    VALUES ('sese.024.001.10', 'MX', 'Securities Settlement Transaction Status Advice', 'MT548', NULL, 'STATUS');

-- Bond Holding table
CREATE TABLE BOND_HOLDING (
    ID              NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ACCOUNT_ID      VARCHAR2(50)  NOT NULL,
    ISIN            VARCHAR2(12)  NOT NULL,
    QUANTITY        NUMBER(18,2)  NOT NULL,
    UPDATED_AT      TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT UK_HOLDING UNIQUE (ACCOUNT_ID, ISIN),
    CONSTRAINT CK_HOLDING_QTY CHECK (QUANTITY >= 0)
);

CREATE INDEX IDX_HOLDING_ACCOUNT ON BOND_HOLDING (ACCOUNT_ID);

-- Audit Log table
CREATE TABLE AUDIT_LOG (
    ID              NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TRADE_REF       VARCHAR2(50),
    EVENT_TYPE      VARCHAR2(50)  NOT NULL,
    DETAIL          CLOB,
    CREATED_AT      TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE INDEX IDX_AUDIT_TRADE_REF ON AUDIT_LOG (TRADE_REF);
CREATE INDEX IDX_AUDIT_EVENT_TYPE ON AUDIT_LOG (EVENT_TYPE);

-- Security Movement ledger (append-only audit journal for position changes)
CREATE TABLE SECURITY_MOVEMENT (
    ID              NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ACCOUNT_ID      VARCHAR2(50)  NOT NULL,
    ISIN            VARCHAR2(12)  NOT NULL,
    MOVEMENT_TYPE   VARCHAR2(6)   NOT NULL,
    QUANTITY        NUMBER(18,2)  NOT NULL,
    BALANCE_AFTER   NUMBER(18,2)  NOT NULL,
    TRADE_REF       VARCHAR2(50)  NOT NULL,
    CREATED_AT      TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT CK_MOVEMENT_TYPE CHECK (MOVEMENT_TYPE IN ('CREDIT', 'DEBIT')),
    CONSTRAINT CK_MOVEMENT_QTY CHECK (QUANTITY > 0),
    CONSTRAINT CK_MOVEMENT_BAL CHECK (BALANCE_AFTER >= 0)
);

CREATE INDEX IDX_MOVEMENT_ACCOUNT_ISIN ON SECURITY_MOVEMENT (ACCOUNT_ID, ISIN);
CREATE INDEX IDX_MOVEMENT_TRADE_REF ON SECURITY_MOVEMENT (TRADE_REF);
CREATE INDEX IDX_MOVEMENT_CREATED_AT ON SECURITY_MOVEMENT (CREATED_AT);

-- EOD Position Snapshot (per-position daily baseline for bounded reconciliation)
CREATE TABLE EOD_POSITION_SNAPSHOT (
    ID              NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    BUSINESS_DATE   DATE          NOT NULL,
    ACCOUNT_ID      VARCHAR2(50)  NOT NULL,
    ISIN            VARCHAR2(12)  NOT NULL,
    BALANCE         NUMBER(18,2)  NOT NULL,
    CREATED_AT      TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT UK_EOD_POS UNIQUE (BUSINESS_DATE, ACCOUNT_ID, ISIN)
);

CREATE INDEX IDX_EOD_POS_DATE ON EOD_POSITION_SNAPSHOT (BUSINESS_DATE);

-- Reconciliation snapshot (records each reconciliation run)
CREATE TABLE RECONCILIATION_SNAPSHOT (
    ID                NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    SNAPSHOT_TYPE     VARCHAR2(20)  NOT NULL,
    POSITIONS_CHECKED NUMBER(10)    NOT NULL,
    DISCREPANCY_COUNT NUMBER(10)    NOT NULL,
    IS_CONSISTENT     NUMBER(1)     NOT NULL,
    CREATED_AT        TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT CK_SNAPSHOT_TYPE CHECK (SNAPSHOT_TYPE IN ('DAILY_CLOSE', 'INCREMENTAL'))
);

CREATE INDEX IDX_SNAPSHOT_CREATED_AT ON RECONCILIATION_SNAPSHOT (CREATED_AT DESC);
