-- Bond Settlement System - Oracle DDL

-- Settlement Instruction table (business entity — message-format agnostic)
CREATE TABLE SETTLEMENT_INSTRUCTION (
    ID                  NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TRADE_REF           VARCHAR2(50)  NOT NULL,
    PARTICIPANT_ID      VARCHAR2(50),
    CLIENT_REFERENCE    VARCHAR2(100),
    OPEN_API_REQUEST_HASH VARCHAR2(64),
    ISIN                VARCHAR2(12)  NOT NULL,
    SETTLEMENT_DATE     DATE          NOT NULL,
    QUANTITY            NUMBER(18,2)  NOT NULL,
    COUNTERPARTY        VARCHAR2(100) NOT NULL,
    BIC_CODE            VARCHAR2(11)  NOT NULL,
    DIRECTION           VARCHAR2(10)  NOT NULL,
    STATUS              VARCHAR2(20)  DEFAULT 'PENDING' NOT NULL,
    ACCOUNT_ID          VARCHAR2(50)  NOT NULL,
    PREFERRED_STANDARD  VARCHAR2(5)   DEFAULT 'MT' NOT NULL,
    RETRY_COUNT         NUMBER(3)     DEFAULT 0 NOT NULL,
    FAILURE_REASON      VARCHAR2(1000),
    CREATED_AT          TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT          TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT UK_TRADE_REF UNIQUE (TRADE_REF),
    CONSTRAINT UK_OPEN_API_CLIENT_REF UNIQUE (PARTICIPANT_ID, CLIENT_REFERENCE),
    CONSTRAINT CK_DIRECTION CHECK (DIRECTION IN ('BUY', 'SELL')),
    CURRENCY            VARCHAR2(3)   DEFAULT 'HKD' NOT NULL,
    SETTLEMENT_AMOUNT   NUMBER(18,2),
    PAYMENT_TYPE        VARCHAR2(20)  DEFAULT 'AGAINST_PAYMENT' NOT NULL,
    FINALITY_TIMESTAMP  TIMESTAMP,
    IS_FINAL            NUMBER(1)     DEFAULT 0 NOT NULL,
    CONSTRAINT CK_STATUS CHECK (STATUS IN ('PENDING', 'SUBMITTING', 'SENT', 'MATCHED', 'FAILED', 'RETRYING', 'CANCELLED', 'DVP_LOCKED')),
    CONSTRAINT CK_PREFERRED_STD CHECK (PREFERRED_STANDARD IN ('MT', 'MX')),
    CONSTRAINT CK_INST_CURRENCY CHECK (CURRENCY IN ('HKD', 'USD', 'EUR', 'CNY')),
    CONSTRAINT CK_PAYMENT_TYPE CHECK (PAYMENT_TYPE IN ('AGAINST_PAYMENT', 'FREE_OF_PAYMENT'))
);

CREATE INDEX IDX_INSTRUCTION_STATUS ON SETTLEMENT_INSTRUCTION (STATUS);
CREATE INDEX IDX_INSTRUCTION_ISIN ON SETTLEMENT_INSTRUCTION (ISIN);
CREATE INDEX IDX_INSTRUCTION_DATE ON SETTLEMENT_INSTRUCTION (SETTLEMENT_DATE);

-- SWIFT Message store (decoupled from business entity, supports MT and MX)
CREATE TABLE SWIFT_MESSAGE (
    ID                NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    INSTRUCTION_ID    NUMBER         NOT NULL,
    TRADE_REF         VARCHAR2(50)   NOT NULL,
    MESSAGE_STANDARD  VARCHAR2(5)    NOT NULL,
    MESSAGE_TYPE      VARCHAR2(50)   NOT NULL,
    DIRECTION         VARCHAR2(10)   NOT NULL,
    RAW_PAYLOAD       CLOB           NOT NULL,
    NAMESPACE         VARCHAR2(200),
    BUSINESS_AREA     VARCHAR2(10),
    PARSED_STATUS     VARCHAR2(30),
    PARSED_REASON     VARCHAR2(500),
    SEQUENCE_NO       NUMBER(5)      DEFAULT 1 NOT NULL,
    IS_TRANSLATED     NUMBER(1)      DEFAULT 0 NOT NULL,
    CREATED_AT        TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_MSG_INSTRUCTION FOREIGN KEY (INSTRUCTION_ID)
        REFERENCES SETTLEMENT_INSTRUCTION(ID),
    CONSTRAINT CK_MSG_STANDARD CHECK (MESSAGE_STANDARD IN ('MT', 'MX')),
    CONSTRAINT CK_MSG_DIRECTION CHECK (DIRECTION IN ('OUTBOUND', 'INBOUND'))
);

CREATE INDEX IDX_MSG_INSTRUCTION ON SWIFT_MESSAGE (INSTRUCTION_ID);
CREATE INDEX IDX_MSG_TRADE_REF ON SWIFT_MESSAGE (TRADE_REF);
CREATE INDEX IDX_MSG_TYPE ON SWIFT_MESSAGE (MESSAGE_TYPE, DIRECTION);

-- Message Type Registry (MT ↔ MX mapping and metadata)
CREATE TABLE MESSAGE_TYPE_REGISTRY (
    MESSAGE_TYPE      VARCHAR2(50)   PRIMARY KEY,
    MESSAGE_STANDARD  VARCHAR2(5)    NOT NULL,
    DESCRIPTION       VARCHAR2(200)  NOT NULL,
    MT_EQUIVALENT     VARCHAR2(10),
    MX_EQUIVALENT     VARCHAR2(50),
    CATEGORY          VARCHAR2(30)   NOT NULL,
    IS_ACTIVE         NUMBER(1)      DEFAULT 1 NOT NULL,
    CONSTRAINT CK_REG_STANDARD CHECK (MESSAGE_STANDARD IN ('MT', 'MX')),
    CONSTRAINT CK_REG_CATEGORY CHECK (CATEGORY IN ('SETTLEMENT', 'STATUS', 'HOLDING', 'MOVEMENT', 'CONFIRMATION', 'CORPORATE_ACTION'))
);

INSERT INTO MESSAGE_TYPE_REGISTRY (MESSAGE_TYPE, MESSAGE_STANDARD, DESCRIPTION, MT_EQUIVALENT, MX_EQUIVALENT, CATEGORY)
    VALUES ('MT541', 'MT', 'Receive Against Payment', NULL, 'sese.023.001.09', 'SETTLEMENT');
INSERT INTO MESSAGE_TYPE_REGISTRY (MESSAGE_TYPE, MESSAGE_STANDARD, DESCRIPTION, MT_EQUIVALENT, MX_EQUIVALENT, CATEGORY)
    VALUES ('MT548', 'MT', 'Settlement Status and Processing Advice', NULL, 'sese.024.001.10', 'STATUS');
INSERT INTO MESSAGE_TYPE_REGISTRY (MESSAGE_TYPE, MESSAGE_STANDARD, DESCRIPTION, MT_EQUIVALENT, MX_EQUIVALENT, CATEGORY)
    VALUES ('sese.023.001.09', 'MX', 'Securities Settlement Transaction Instruction', 'MT541', NULL, 'SETTLEMENT');
INSERT INTO MESSAGE_TYPE_REGISTRY (MESSAGE_TYPE, MESSAGE_STANDARD, DESCRIPTION, MT_EQUIVALENT, MX_EQUIVALENT, CATEGORY)
    VALUES ('sese.024.001.10', 'MX', 'Securities Settlement Transaction Status Advice', 'MT548', NULL, 'STATUS');

-- Extended message types (MT540-543 family)
INSERT INTO MESSAGE_TYPE_REGISTRY (MESSAGE_TYPE, MESSAGE_STANDARD, DESCRIPTION, MT_EQUIVALENT, MX_EQUIVALENT, CATEGORY)
    VALUES ('MT540', 'MT', 'Receive Free of Payment', NULL, 'sese.023.001.09', 'SETTLEMENT');
INSERT INTO MESSAGE_TYPE_REGISTRY (MESSAGE_TYPE, MESSAGE_STANDARD, DESCRIPTION, MT_EQUIVALENT, MX_EQUIVALENT, CATEGORY)
    VALUES ('MT542', 'MT', 'Deliver Free of Payment', NULL, 'sese.023.001.09', 'SETTLEMENT');
INSERT INTO MESSAGE_TYPE_REGISTRY (MESSAGE_TYPE, MESSAGE_STANDARD, DESCRIPTION, MT_EQUIVALENT, MX_EQUIVALENT, CATEGORY)
    VALUES ('MT543', 'MT', 'Deliver Against Payment', NULL, 'sese.023.001.09', 'SETTLEMENT');

-- Confirmation messages
INSERT INTO MESSAGE_TYPE_REGISTRY (MESSAGE_TYPE, MESSAGE_STANDARD, DESCRIPTION, MT_EQUIVALENT, MX_EQUIVALENT, CATEGORY)
    VALUES ('sese.025.001.09', 'MX', 'Securities Settlement Transaction Confirmation', 'MT544', NULL, 'CONFIRMATION');
INSERT INTO MESSAGE_TYPE_REGISTRY (MESSAGE_TYPE, MESSAGE_STANDARD, DESCRIPTION, MT_EQUIVALENT, MX_EQUIVALENT, CATEGORY)
    VALUES ('sese.026.001.08', 'MX', 'Securities Settlement Transaction Reversal Advice', 'MT545', NULL, 'CONFIRMATION');

-- Holdings / statement messages
INSERT INTO MESSAGE_TYPE_REGISTRY (MESSAGE_TYPE, MESSAGE_STANDARD, DESCRIPTION, MT_EQUIVALENT, MX_EQUIVALENT, CATEGORY)
    VALUES ('MT535', 'MT', 'Statement of Holdings', NULL, 'semt.002.001.10', 'HOLDING');
INSERT INTO MESSAGE_TYPE_REGISTRY (MESSAGE_TYPE, MESSAGE_STANDARD, DESCRIPTION, MT_EQUIVALENT, MX_EQUIVALENT, CATEGORY)
    VALUES ('semt.002.001.10', 'MX', 'Securities Balance Custody Report', 'MT535', NULL, 'HOLDING');
INSERT INTO MESSAGE_TYPE_REGISTRY (MESSAGE_TYPE, MESSAGE_STANDARD, DESCRIPTION, MT_EQUIVALENT, MX_EQUIVALENT, CATEGORY)
    VALUES ('MT536', 'MT', 'Statement of Transactions', NULL, 'semt.017.001.10', 'MOVEMENT');
INSERT INTO MESSAGE_TYPE_REGISTRY (MESSAGE_TYPE, MESSAGE_STANDARD, DESCRIPTION, MT_EQUIVALENT, MX_EQUIVALENT, CATEGORY)
    VALUES ('semt.017.001.10', 'MX', 'Securities Transaction Posting Report', 'MT536', NULL, 'MOVEMENT');

-- Corporate action messages
INSERT INTO MESSAGE_TYPE_REGISTRY (MESSAGE_TYPE, MESSAGE_STANDARD, DESCRIPTION, MT_EQUIVALENT, MX_EQUIVALENT, CATEGORY)
    VALUES ('MT564', 'MT', 'Corporate Action Notification', NULL, 'seev.031.001.11', 'CORPORATE_ACTION');
INSERT INTO MESSAGE_TYPE_REGISTRY (MESSAGE_TYPE, MESSAGE_STANDARD, DESCRIPTION, MT_EQUIVALENT, MX_EQUIVALENT, CATEGORY)
    VALUES ('seev.031.001.11', 'MX', 'Corporate Action Notification', 'MT564', NULL, 'CORPORATE_ACTION');
INSERT INTO MESSAGE_TYPE_REGISTRY (MESSAGE_TYPE, MESSAGE_STANDARD, DESCRIPTION, MT_EQUIVALENT, MX_EQUIVALENT, CATEGORY)
    VALUES ('MT566', 'MT', 'Corporate Action Confirmation', NULL, 'seev.036.001.11', 'CORPORATE_ACTION');
INSERT INTO MESSAGE_TYPE_REGISTRY (MESSAGE_TYPE, MESSAGE_STANDARD, DESCRIPTION, MT_EQUIVALENT, MX_EQUIVALENT, CATEGORY)
    VALUES ('seev.036.001.11', 'MX', 'Corporate Action Confirmation', 'MT566', NULL, 'CORPORATE_ACTION');

-- Bond Holding table
CREATE TABLE BOND_HOLDING (
    ID              NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ACCOUNT_ID      VARCHAR2(50)  NOT NULL,
    ISIN            VARCHAR2(12)  NOT NULL,
    QUANTITY        NUMBER(18,2)  NOT NULL,
    UPDATED_AT      TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT UK_HOLDING UNIQUE (ACCOUNT_ID, ISIN),
    CONSTRAINT CK_HOLDING_QTY CHECK (QUANTITY >= 0)
);

CREATE INDEX IDX_HOLDING_ACCOUNT ON BOND_HOLDING (ACCOUNT_ID);

-- Audit Log table
CREATE TABLE AUDIT_LOG (
    ID              NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TRADE_REF       VARCHAR2(50),
    EVENT_TYPE      VARCHAR2(50)  NOT NULL,
    DETAIL          CLOB,
    CREATED_AT      TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE INDEX IDX_AUDIT_TRADE_REF ON AUDIT_LOG (TRADE_REF);
CREATE INDEX IDX_AUDIT_EVENT_TYPE ON AUDIT_LOG (EVENT_TYPE);

-- Security Movement ledger (append-only audit journal for position changes)
CREATE TABLE SECURITY_MOVEMENT (
    ID              NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ACCOUNT_ID      VARCHAR2(50)  NOT NULL,
    ISIN            VARCHAR2(12)  NOT NULL,
    MOVEMENT_TYPE   VARCHAR2(6)   NOT NULL,
    QUANTITY        NUMBER(18,2)  NOT NULL,
    BALANCE_AFTER   NUMBER(18,2)  NOT NULL,
    TRADE_REF       VARCHAR2(50)  NOT NULL,
    CREATED_AT      TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT CK_MOVEMENT_TYPE CHECK (MOVEMENT_TYPE IN ('CREDIT', 'DEBIT')),
    CONSTRAINT CK_MOVEMENT_QTY CHECK (QUANTITY > 0),
    CONSTRAINT CK_MOVEMENT_BAL CHECK (BALANCE_AFTER >= 0)
);

CREATE INDEX IDX_MOVEMENT_ACCOUNT_ISIN ON SECURITY_MOVEMENT (ACCOUNT_ID, ISIN);
CREATE INDEX IDX_MOVEMENT_TRADE_REF ON SECURITY_MOVEMENT (TRADE_REF);
CREATE INDEX IDX_MOVEMENT_CREATED_AT ON SECURITY_MOVEMENT (CREATED_AT);

-- EOD Position Snapshot (per-position daily baseline for bounded reconciliation)
CREATE TABLE EOD_POSITION_SNAPSHOT (
    ID              NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    BUSINESS_DATE   DATE          NOT NULL,
    ACCOUNT_ID      VARCHAR2(50)  NOT NULL,
    ISIN            VARCHAR2(12)  NOT NULL,
    BALANCE         NUMBER(18,2)  NOT NULL,
    CREATED_AT      TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT UK_EOD_POS UNIQUE (BUSINESS_DATE, ACCOUNT_ID, ISIN)
);

CREATE INDEX IDX_EOD_POS_DATE ON EOD_POSITION_SNAPSHOT (BUSINESS_DATE);

-- Reconciliation snapshot (records each reconciliation run)
CREATE TABLE RECONCILIATION_SNAPSHOT (
    ID                NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    SNAPSHOT_TYPE     VARCHAR2(20)  NOT NULL,
    POSITIONS_CHECKED NUMBER(10)    NOT NULL,
    DISCREPANCY_COUNT NUMBER(10)    NOT NULL,
    IS_CONSISTENT     NUMBER(1)     NOT NULL,
    CREATED_AT        TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT CK_SNAPSHOT_TYPE CHECK (SNAPSHOT_TYPE IN ('DAILY_CLOSE', 'INCREMENTAL'))
);

CREATE INDEX IDX_SNAPSHOT_CREATED_AT ON RECONCILIATION_SNAPSHOT (CREATED_AT DESC);

-- Counterparty capability registry (MT↔MX coexistence routing)
CREATE TABLE COUNTERPARTY_CAPABILITY (
    BIC_CODE           VARCHAR2(11)  PRIMARY KEY,
    PARTICIPANT_NAME   VARCHAR2(100) NOT NULL,
    SUPPORTED_STANDARD VARCHAR2(10)  DEFAULT 'DUAL' NOT NULL,
    PREFERRED_STANDARD VARCHAR2(5)   DEFAULT 'MT' NOT NULL,
    EFFECTIVE_DATE     DATE          DEFAULT SYSDATE NOT NULL,
    IS_ACTIVE          NUMBER(1)     DEFAULT 1 NOT NULL,
    CONSTRAINT CK_CAP_SUPPORTED CHECK (SUPPORTED_STANDARD IN ('MT_ONLY', 'MX_ONLY', 'DUAL')),
    CONSTRAINT CK_CAP_PREFERRED CHECK (PREFERRED_STANDARD IN ('MT', 'MX'))
);

-- ============================================================
-- DVP (Delivery vs Payment) — Cash Leg Tables
-- ============================================================

CREATE TABLE CASH_ACCOUNT (
    ID              NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ACCOUNT_ID      VARCHAR2(50)  NOT NULL,
    CURRENCY        VARCHAR2(3)   NOT NULL,
    BALANCE         NUMBER(18,2)  DEFAULT 0 NOT NULL,
    UPDATED_AT      TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT UK_CASH_ACCOUNT UNIQUE (ACCOUNT_ID, CURRENCY),
    CONSTRAINT CK_CASH_CURRENCY CHECK (CURRENCY IN ('HKD', 'USD', 'EUR', 'CNY')),
    CONSTRAINT CK_CASH_BALANCE CHECK (BALANCE >= 0)
);

CREATE INDEX IDX_CASH_ACCOUNT_ID ON CASH_ACCOUNT (ACCOUNT_ID);

CREATE TABLE CASH_MOVEMENT (
    ID              NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ACCOUNT_ID      VARCHAR2(50)  NOT NULL,
    CURRENCY        VARCHAR2(3)   NOT NULL,
    MOVEMENT_TYPE   VARCHAR2(6)   NOT NULL,
    AMOUNT          NUMBER(18,2)  NOT NULL,
    BALANCE_AFTER   NUMBER(18,2)  NOT NULL,
    TRADE_REF       VARCHAR2(50)  NOT NULL,
    CREATED_AT      TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT CK_CASH_MVT_TYPE CHECK (MOVEMENT_TYPE IN ('CREDIT', 'DEBIT')),
    CONSTRAINT CK_CASH_MVT_AMT CHECK (AMOUNT > 0),
    CONSTRAINT CK_CASH_MVT_BAL CHECK (BALANCE_AFTER >= 0)
);

CREATE INDEX IDX_CASH_MVT_ACCOUNT ON CASH_MOVEMENT (ACCOUNT_ID, CURRENCY);
CREATE INDEX IDX_CASH_MVT_TRADE_REF ON CASH_MOVEMENT (TRADE_REF);

-- ============================================================
-- Matching Engine — Bilateral Instruction Matching
-- ============================================================

CREATE TABLE MATCHING_INSTRUCTION (
    ID                NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TRADE_REF         VARCHAR2(50)  NOT NULL,
    ISIN              VARCHAR2(12)  NOT NULL,
    SETTLEMENT_DATE   DATE          NOT NULL,
    QUANTITY          NUMBER(18,2)  NOT NULL,
    AMOUNT            NUMBER(18,2),
    CURRENCY          VARCHAR2(3)   DEFAULT 'HKD',
    COUNTERPARTY_BIC  VARCHAR2(11)  NOT NULL,
    SUBMITTER_BIC     VARCHAR2(11)  NOT NULL,
    DIRECTION         VARCHAR2(10)  NOT NULL,
    MATCHING_STATUS   VARCHAR2(20)  DEFAULT 'UNMATCHED' NOT NULL,
    MATCHED_WITH_ID   NUMBER,
    INSTRUCTION_ID    NUMBER,
    CREATED_AT        TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT        TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT CK_MI_DIRECTION CHECK (DIRECTION IN ('BUY', 'SELL')),
    CONSTRAINT CK_MI_STATUS CHECK (MATCHING_STATUS IN ('UNMATCHED', 'MATCHED', 'ALLEGED', 'CANCELLED')),
    CONSTRAINT FK_MI_MATCHED FOREIGN KEY (MATCHED_WITH_ID)
        REFERENCES MATCHING_INSTRUCTION(ID),
    CONSTRAINT FK_MI_INSTRUCTION FOREIGN KEY (INSTRUCTION_ID)
        REFERENCES SETTLEMENT_INSTRUCTION(ID)
);

CREATE INDEX IDX_MI_ISIN_DATE ON MATCHING_INSTRUCTION (ISIN, SETTLEMENT_DATE);
CREATE INDEX IDX_MI_STATUS ON MATCHING_INSTRUCTION (MATCHING_STATUS);
CREATE INDEX IDX_MI_COUNTERPARTY ON MATCHING_INSTRUCTION (COUNTERPARTY_BIC);
