-- Bond Settlement System - Oracle DDL

-- Settlement Instruction table
CREATE TABLE SETTLEMENT_INSTRUCTION (
    ID              NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TRADE_REF       VARCHAR2(50)  NOT NULL,
    ISIN            VARCHAR2(12)  NOT NULL,
    SETTLEMENT_DATE DATE          NOT NULL,
    QUANTITY        NUMBER(18,2)  NOT NULL,
    COUNTERPARTY    VARCHAR2(100) NOT NULL,
    BIC_CODE        VARCHAR2(11)  NOT NULL,
    DIRECTION       VARCHAR2(10)  NOT NULL,
    STATUS          VARCHAR2(20)  DEFAULT 'PENDING' NOT NULL,
    ACCOUNT_ID      VARCHAR2(50)  NOT NULL,
    MT541_RAW       CLOB,
    MT548_RAW       CLOB,
    RETRY_COUNT     NUMBER(3)     DEFAULT 0 NOT NULL,
    FAILURE_REASON  VARCHAR2(1000),
    CREATED_AT      TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT      TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT UK_TRADE_REF UNIQUE (TRADE_REF),
    CONSTRAINT CK_DIRECTION CHECK (DIRECTION IN ('BUY', 'SELL')),
    CONSTRAINT CK_STATUS CHECK (STATUS IN ('PENDING', 'SUBMITTING', 'SENT', 'MATCHED', 'FAILED', 'CANCELLED'))
);

CREATE INDEX IDX_INSTRUCTION_STATUS ON SETTLEMENT_INSTRUCTION (STATUS);
CREATE INDEX IDX_INSTRUCTION_ISIN ON SETTLEMENT_INSTRUCTION (ISIN);
CREATE INDEX IDX_INSTRUCTION_DATE ON SETTLEMENT_INSTRUCTION (SETTLEMENT_DATE);

-- Bond Holding table
CREATE TABLE BOND_HOLDING (
    ID              NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ACCOUNT_ID      VARCHAR2(50)  NOT NULL,
    ISIN            VARCHAR2(12)  NOT NULL,
    QUANTITY        NUMBER(18,2)  NOT NULL,
    UPDATED_AT      TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT UK_HOLDING UNIQUE (ACCOUNT_ID, ISIN),
    CONSTRAINT CK_HOLDING_QTY CHECK (QUANTITY >= 0)
);

CREATE INDEX IDX_HOLDING_ACCOUNT ON BOND_HOLDING (ACCOUNT_ID);

-- Audit Log table
CREATE TABLE AUDIT_LOG (
    ID              NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TRADE_REF       VARCHAR2(50),
    EVENT_TYPE      VARCHAR2(50)  NOT NULL,
    DETAIL          CLOB,
    CREATED_AT      TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE INDEX IDX_AUDIT_TRADE_REF ON AUDIT_LOG (TRADE_REF);
CREATE INDEX IDX_AUDIT_EVENT_TYPE ON AUDIT_LOG (EVENT_TYPE);

-- Security Movement ledger (append-only, source of truth for positions)
CREATE TABLE SECURITY_MOVEMENT (
    ID              NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ACCOUNT_ID      VARCHAR2(50)  NOT NULL,
    ISIN            VARCHAR2(12)  NOT NULL,
    MOVEMENT_TYPE   VARCHAR2(6)   NOT NULL,
    QUANTITY        NUMBER(18,2)  NOT NULL,
    BALANCE_AFTER   NUMBER(18,2)  NOT NULL,
    TRADE_REF       VARCHAR2(50)  NOT NULL,
    CREATED_AT      TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT CK_MOVEMENT_TYPE CHECK (MOVEMENT_TYPE IN ('CREDIT', 'DEBIT')),
    CONSTRAINT CK_MOVEMENT_QTY CHECK (QUANTITY > 0),
    CONSTRAINT CK_MOVEMENT_BAL CHECK (BALANCE_AFTER >= 0)
);

CREATE INDEX IDX_MOVEMENT_ACCOUNT_ISIN ON SECURITY_MOVEMENT (ACCOUNT_ID, ISIN);
CREATE INDEX IDX_MOVEMENT_TRADE_REF ON SECURITY_MOVEMENT (TRADE_REF);
CREATE INDEX IDX_MOVEMENT_CREATED_AT ON SECURITY_MOVEMENT (CREATED_AT);

-- Reconciliation snapshot (records each reconciliation run)
CREATE TABLE RECONCILIATION_SNAPSHOT (
    ID                NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    SNAPSHOT_TYPE     VARCHAR2(20)  NOT NULL,
    POSITIONS_CHECKED NUMBER(10)    NOT NULL,
    DISCREPANCY_COUNT NUMBER(10)    NOT NULL,
    IS_CONSISTENT     NUMBER(1)     NOT NULL,
    CREATED_AT        TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT CK_SNAPSHOT_TYPE CHECK (SNAPSHOT_TYPE IN ('DAILY_CLOSE', 'INCREMENTAL'))
);

CREATE INDEX IDX_SNAPSHOT_CREATED_AT ON RECONCILIATION_SNAPSHOT (CREATED_AT DESC);
